name: Twitter Daily Bot

on:
  schedule:
    - cron: '0 20 * * *'  # 11 مساءً بتوقيت اليمن (8 PM UTC)
    - cron: '0 1 * * *'   # 4 فجراً بتوقيت اليمن (1 AM UTC) 
    - cron: '0 5 * * *'   # 8 صباحاً بتوقيت اليمن (5 AM UTC)
    - cron: '0 13 * * *'  # 4 مساءً بتوقيت اليمن (1 PM UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run Twitter Bot
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      run: python bot.py
